exclude_patterns:
- "cypress/**"
- "**/*.test.*"
- "**/*.stories.*"
- "**/config/**"
- "**/fixture*"
- "scripts/lighthouseBudget.js"
- "scripts/lighthouseConfig.js"
- "src/index.js"
- "src/server/index.jsx"
- "src/app/components/Metadata/index.jsx"
- "src/app/containers/ATIAnalytics/atiUrl.js"
- "src/app/containers/ATIAnalytics/amp/index.jsx"
- "src/app/containers/Figure/index.jsx"
- "src/app/components/ConsentBanner/index.jsx"
- "src/app/containers/ConsentBanner/index.amp.jsx"
- "src/app/Layouts/defaultPageWrapper.jsx"
- "src/app/contexts/RequestContext/index.jsx"
- "src/app/components/ErrorPage/index.jsx"
- "src/app/lib/styledGrid/index.jsx"
- "src/server/Document/component.jsx"
- "src/app/containers/ErrorMain/index.jsx"
- "src/app/containers/Navigation/index.jsx"
