engines:
  duplication:
    enabled: true
    exclude_patterns:
      - "src/**/*.{stories,test).{js,jsx}"
      - "cypress/{integration,support}/*.js"
exclude_patterns:
  - "**/node_modules/""
  - "src/app/lib/config/""
  - "src/app/**/fixtures.js"
