version: "2"
plugins:
  duplication:
    enabled: true
    exclude_patterns:
      # - "src/**/*.stories.jsx"
      # - "src/**/*.test.js"
      # - "src/**/*.test.jsx"
      - "cypress/{integration,support}/*.js"
exclude_patterns:
  - "**/node_modules/"
  - "src/app/lib/config/"
  - "src/app/**/fixtures.js"
