version: '2'
plugins:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
    exclude_patterns:
      # the line below should work but doesn't it removes all js and jsx code coverage
      # - 'src/**/*.{test,stories}.{js,jsx}'
      - 'cypress/{integration,support}/*.js'
exclude_patterns:
  - '**/node_modules/'
  - 'src/app/lib/config/'
  - 'src/app/**/fixtures.js'
