engines:
  duplication:
    enabled: true
    exclude_patterns:
      - 'src/**/*.test.{jsx,js}'
      - 'cypress/{integration,support}/*.js'
exclude_patterns:
  - '**/node_modules/'
  - 'src/app/lib/config/'
  - 'src/app/**/fixtures.js'
