ci:
  collect:
    numberOfRuns: 3
    startServerCommand: npm start
    url:
      - http://localhost:7080/mundo # Frontpage
      - http://localhost:7080/news/articles/c0g992jmmkko # Article
      - http://localhost:7080/mundo/23263889 # CPS STY
      - http://localhost:7080/pidgin/sport-23252855 # CPS PGL
  assert:
    assertions:
      categories:performance: off
      categories:pwa: off
      categories:accessibility:
        - error
        - aggregationMethod: optimisitc
          minScore: 0.9
      categories:bestpractices:
        - error
        - aggregationMethod: optimistic
          minScore: 0.9
      categories:seo:
        - error
        - aggregationMethod: optimistic
          minScore: 0.9
    skipAudits:
      - is-on-https
  upload:
    target: temporary-public-storage
