version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - npm ci
      - npm run build
  build:
    commands:
      - CYPRESS_SMOKE=false CYPRESS_APP_ENV=live npm run cypress:ci
reports:
  JunitReportsTest:
    files:
      - '**/*'
    base-directory: 'cypress/results' # Location of the reports
